name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Step to checkout the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js for the workflow
        with:
          node-version: '16'  # You can change this to the Node.js version you need

      - name: Install dependencies
        run: npm install  # Install dependencies from package.json

      - name: Build the project with environment variables
        run: |
          # Debug: Print out the environment variables before the build
          echo "VITE_OPENWEATHERMAP=$VITE_OPENWEATHERMAP"
          echo "VITE_GEOAPIFY=$VITE_GEOAPIFY"
          npm run build  # Run the build process using Vite
        env:
          # Pass the GitHub secrets to environment variables
          VITE_OPENWEATHERMAP: ${{ secrets.OPENWEATHERMAP_KEY }}
          VITE_GEOAPIFY: ${{ secrets.GEOAPIFY_KEY }}
          VITE_DISTANCEMATRIX: ${{ secrets.DISTANCEMATRIX_KEY }}
          VITE_DISTANCEMATRIX_COORDS: ${{ secrets.DISTANCEMATRIX_COORDS_KEY }}
          VITE_VISUALCROSSING: ${{ secrets.VISUALCROSSING_KEY }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Action to deploy to GitHub Pages
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: .  # The folder where your built files will be located (Vite outputs to 'dist')
          token: ${{ secrets.GH_TOKEN }}  # Pass the GitHub token for deployment
